# Generated by Django 3.2.4 on 2021-07-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        ('authentication', '0003_user_fav_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todos_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todo'),
        ),
    ]
