# Generated by Django 3.2.4 on 2021-07-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        ('authentication', '0005_alter_user_todos_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='todos_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.todo'),
        ),
    ]
