# Generated by Django 3.2.4 on 2021-07-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_todos_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='todos_list',
        ),
    ]
