# Generated by Django 2.2.24 on 2021-12-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_fav_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fav_color',
            new_name='identifier',
        ),
    ]
