# Generated by Django 2.2.24 on 2021-12-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211211_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grupa_sanguina',
            field=models.CharField(choices=[('1', ''), ('2', 'O+'), ('3', 'O-'), ('4', 'A+'), ('5', 'A-'), ('6', 'B+'), ('7', 'B-'), ('8', 'AB+'), ('9', 'AB-')], default='1', max_length=20),
        ),
    ]
