# Generated by Django 2.2.24 on 2021-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_grupa_sanguina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupa_sanguina',
            field=models.CharField(max_length=20),
        ),
    ]
