# Generated by Django 2.2.24 on 2021-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211211_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupa_sanguina',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
