# Generated by Django 2.2.24 on 2021-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=20)),
            ],
        ),
    ]
