# Generated by Django 2.2.24 on 2022-01-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment_type',
            field=models.CharField(max_length=6),
        ),
    ]
