# Generated by Django 2.2.24 on 2022-01-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20220107_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment_type',
            field=models.CharField(max_length=20),
        ),
    ]
