# Generated by Django 2.2.24 on 2022-01-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patient',
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Room')),
            ],
        ),
    ]
