# Generated by Django 2.2.24 on 2022-01-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_auto_20220110_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Patient'),
        ),
    ]
