# Generated by Django 2.2.24 on 2022-01-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_auto_20220110_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalization',
            name='occupied_beds',
            field=models.IntegerField(null=True),
        ),
    ]
