# Generated by Django 2.2.24 on 2022-01-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_hospitalization_occupied_beds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalization',
            old_name='occupied_beds',
            new_name='occupied_bed',
        ),
    ]
